[package]
name = "hello-world"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
bs58 = "0.5.1"
serde = "1.0.219"
serde_json = "1.0.140"
solana-client = "2.3.2"
solana-program = "2.3.0"
solana-sdk = "2.0.0"
solana-transaction-status = "2.3.2"
